export interface VocabTopicWord {
  id: string;
  word: string;
  phonetic: string;
  partOfSpeech: "noun" | "verb" | "adjective" | "adverb" | "phrase";
  level: "B1" | "B2" | "C1" | "C2";
  meaning: string;
  definition: string;
  example: string;
  collocations: string[];
  contextTip?: string;
  topicId: string;
  emoji?: string;
}

export interface VocabTopic {
  id: string;
  name: string;
  vietnameseName: string;
  description: string;
  iconName: "Briefcase" | "Handshake" | "Cpu" | "Megaphone" | "TrendingUp" | "Brain" | "Compass";
  level: "B1" | "B2" | "C1" | "C2";
  accentColor: string;
  words: VocabTopicWord[];
}

export const VOCAB_TOPICS: VocabTopic[] = [
  {
    id: "corporate-strategy",
    name: "Corporate Strategy & Operations",
    vietnameseName: "Chiến Lược & Quản Trị Doanh Nghiệp",
    description: "Từ vựng điều hành, hoạch định chiến lược kinh doanh và tối ưu vận hành tổ chức.",
    iconName: "Briefcase",
    level: "C1",
    accentColor: "indigo",
    words: [
      {
        id: "cs-1",
        word: "Synergy",
        phonetic: "/ˈsɪnədʒi/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Sự cộng hưởng, hiệu ứng tương hỗ tạo ra giá trị lớn hơn tổng thể",
        definition: "The combined power of a group of things when they are working together which is greater than the total power achieved by each working separately.",
        example: "The merger between the two fintech firms created significant operational synergies.",
        collocations: ["create synergy", "exploit synergy", "cross-functional synergy"],
        contextTip: "Thường dùng trong báo cáo M&A hoặc đề xuất hợp tác giữa các phòng ban.",
        topicId: "corporate-strategy",
        emoji: "⚡",
      },
      {
        id: "cs-2",
        word: "Benchmark",
        phonetic: "/ˈbentʃmɑːrk/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Tiêu chuẩn đối sánh, mốc chuẩn mực để đo lường hiệu suất",
        definition: "A standard or point of reference against which things may be compared or assessed.",
        example: "Our quarterly NPS score serves as a benchmark for client satisfaction across the division.",
        collocations: ["industry benchmark", "set a benchmark", "benchmark against competitors"],
        contextTip: "Dùng cả ở dạng động từ (to benchmark performance against...).",
        topicId: "corporate-strategy",
        emoji: "📊",
      },
      {
        id: "cs-3",
        word: "Leverage",
        phonetic: "/ˈliːvərɪdʒ/",
        partOfSpeech: "verb",
        level: "C1",
        meaning: "Tận dụng tối đa nguồn lực hoặc ưu thế để tạo bước ngoặt",
        definition: "To use something to maximum advantage to achieve strategic outcomes.",
        example: "We can leverage our existing distribution network to launch the new enterprise product line.",
        collocations: ["leverage assets", "leverage expertise", "gain leverage"],
        contextTip: "Từ vựng vàng của các giám đốc điều hành thay cho từ 'use' đơn điệu.",
        topicId: "corporate-strategy",
        emoji: "🏗️",
      },
      {
        id: "cs-4",
        word: "Scalability",
        phonetic: "/ˌskeɪləˈbɪləti/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Khả năng mở rộng quy mô mà không làm giảm hiệu suất hay tăng chi phí phi mã",
        definition: "The capacity to be changed in size or scale to handle growing volume.",
        example: "Investors were impressed by the scalability of our SaaS architecture.",
        collocations: ["ensure scalability", "limit scalability", "high scalability"],
        contextTip: "Rất phổ biến trong pitching startup, công nghệ đám mây và mô hình kinh doanh.",
        topicId: "corporate-strategy",
        emoji: "📈",
      },
      {
        id: "cs-5",
        word: "Bottleneck",
        phonetic: "/ˈbɒtlnek/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Điểm nghẽn, khâu tắc nghẽn làm chậm toàn bộ tiến độ",
        definition: "A point of congestion in a system that occurs when workloads arrive too quickly for the production process to handle.",
        example: "The manual QA testing phase has become the primary bottleneck in our deployment pipeline.",
        collocations: ["identify bottlenecks", "eliminate bottlenecks", "traffic/workflow bottleneck"],
        contextTip: "Dùng để phân tích nguyên nhân chậm tiến độ dự án một cách khách quan.",
        topicId: "corporate-strategy",
        emoji: "⏳",
      },
      {
        id: "cs-6",
        word: "Feasibility",
        phonetic: "/ˌfiːzəˈbɪləti/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Tính khả thi, khả năng thực hiện thành công trong thực tế",
        definition: "The state or degree of being easily or conveniently done.",
        example: "We commissioned a feasibility study before committing capital to the European expansion.",
        collocations: ["feasibility study", "assess feasibility", "economic feasibility"],
        contextTip: "Luôn đi kèm với cụm 'conduct/commission a feasibility study'.",
        topicId: "corporate-strategy",
        emoji: "📋",
      },
      {
        id: "cs-7",
        word: "Stakeholder",
        phonetic: "/ˈsteɪkhoʊldər/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Bên liên quan, đối tượng có quyền lợi gắn liền với dự án",
        definition: "A person with an interest or concern in something, especially a business.",
        example: "We held a town hall to align key stakeholders on the new governance policies.",
        collocations: ["key stakeholder", "stakeholder engagement", "stakeholder consensus"],
        contextTip: "Bao gồm khách hàng, cổ đông, nhân sự và đối tác điều hành.",
        topicId: "corporate-strategy",
        emoji: "👥",
      },
      {
        id: "cs-8",
        word: "Deliverable",
        phonetic: "/dɪˈlɪvərəbl/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Sản phẩm bàn giao, hạng mục đầu ra cụ thể cam kết trong hợp đồng/dự án",
        definition: "A thing able to be provided, especially as a product of a development process.",
        example: "The design team submitted all sprint deliverables two days ahead of schedule.",
        collocations: ["key deliverable", "final deliverable", "agree on deliverables"],
        contextTip: "Từ chuẩn văn phòng quốc tế thay vì nói chung chung 'work' hay 'results'.",
        topicId: "corporate-strategy",
        emoji: "📦",
      },
      {
        id: "cs-9",
        word: "Paradigm",
        phonetic: "/ˈpærədaɪm/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Mô thức, khuôn mẫu tư duy định hình cách vận hành của cả một ngành",
        definition: "A typical example or pattern of something; a distinct set of concepts or thought patterns.",
        example: "Generative AI represents a fundamental paradigm shift in how knowledge workers operate.",
        collocations: ["paradigm shift", "dominant paradigm", "new paradigm"],
        contextTip: "Cụm 'paradigm shift' (chuyển dịch mô thức) mang phong thái tư duy lãnh đạo cấp cao.",
        topicId: "corporate-strategy",
        emoji: "🔄",
      },
      {
        id: "cs-10",
        word: "Initiative",
        phonetic: "/ɪˈnɪʃətɪv/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Sáng kiến chiến lược, hành động tiên phong giải quyết vấn đề",
        definition: "An act or strategy intended to resolve a difficulty or improve a situation; a fresh approach.",
        example: "Our sustainability initiative helped reduce cloud server emissions by forty percent.",
        collocations: ["launch an initiative", "take the initiative", "strategic initiative"],
        contextTip: "'Take the initiative' nghĩa là chủ động tiên phong, không đợi cấp trên nhắc nhở.",
        topicId: "corporate-strategy",
        emoji: "💡",
      },
    ],
  },
  {
    id: "negotiation-persuasion",
    name: "High-Stakes Negotiation & Contracts",
    vietnameseName: "Đàm Phán & Thuyết Phục Đối Tác",
    description: "Bộ từ vựng đàm phán hợp đồng thương mại, thương lượng điều khoản và dung hòa lợi ích.",
    iconName: "Handshake",
    level: "C1",
    accentColor: "emerald",
    words: [
      {
        id: "np-1",
        word: "Concession",
        phonetic: "/kənˈseʃn/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Sự nhượng bộ, điều khoản chịu lùi một bước để đạt thỏa thuận chung",
        definition: "A thing that is granted, especially in response to demands, in a negotiation.",
        example: "We offered a five percent discount as a concession in exchange for a three-year contract commitment.",
        collocations: ["make a concession", "win concessions", "mutual concessions"],
        contextTip: "Nghệ thuật đàm phán: không bao giờ 'concede' mà không đòi hỏi đối phương nhượng bộ ngược lại.",
        topicId: "negotiation-persuasion",
        emoji: "🤝",
      },
      {
        id: "np-2",
        word: "Consensus",
        phonetic: "/kənˈsensəs/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Sự đồng thuận chung, thỏa thuận nhất trí giữa các bên tham gia",
        definition: "A general agreement among a group of people.",
        example: "After three hours of deliberations, the board reached a unanimous consensus on the pricing model.",
        collocations: ["reach a consensus", "broad consensus", "build consensus"],
        contextTip: "Thường đi kèm động từ 'reach' hoặc 'build' consensus.",
        topicId: "negotiation-persuasion",
        emoji: "🕊️",
      },
      {
        id: "np-3",
        word: "Deadlock",
        phonetic: "/ˈdedlɒk/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Tình thế bế tắc, khi không bên nào chịu thỏa hiệp",
        definition: "A situation, typically one involving opposing parties, in which no progress can be made.",
        example: "The negotiations reached a deadlock over intellectual property indemnification rights.",
        collocations: ["break the deadlock", "reach a deadlock", "negotiation deadlock"],
        contextTip: "Cụm 'break the deadlock' (phá vỡ thế bế tắc) là mẫu câu đàm phán đắt giá.",
        topicId: "negotiation-persuasion",
        emoji: "🔒",
      },
      {
        id: "np-4",
        word: "Counteroffer",
        phonetic: "/ˈkaʊntərˌɔːfər/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Lời đề nghị phản hồi, mức chào giá đối ứng",
        definition: "An offer made in response to another offer during a business transaction.",
        example: "Their legal team reviewed our proposal and submitted a counteroffer within forty-eight hours.",
        collocations: ["make a counteroffer", "reject a counteroffer", "acceptable counteroffer"],
        contextTip: "Dùng cả như động từ và danh từ trong thương lượng lương và hợp đồng.",
        topicId: "negotiation-persuasion",
        emoji: "🔄",
      },
      {
        id: "np-5",
        word: "Goodwill",
        phonetic: "/ˌɡʊdˈwɪl/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Thiện chí hợp tác hoặc giá trị uy tín vô hình của thương hiệu",
        definition: "Friendly, helpful, or cooperative feelings; the established reputation of a business regarded as a quantifiable asset.",
        example: "As a gesture of goodwill, we waived the onboarding fee for their first quarter.",
        collocations: ["gesture of goodwill", "generate goodwill", "preserve goodwill"],
        contextTip: "'As a gesture of goodwill' là cách nói lịch thiệp khi tặng kèm ưu đãi cho đối tác.",
        topicId: "negotiation-persuasion",
        emoji: "✨",
      },
      {
        id: "np-6",
        word: "Clause",
        phonetic: "/klɔːz/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Điều khoản trong văn bản pháp lý hoặc hợp đồng kinh tế",
        definition: "A particular and separate article, stipulation, or proviso in a treaty, bill, or contract.",
        example: "Please ensure that the confidentiality clause protects our proprietary source code.",
        collocations: ["confidentiality clause", "penalty clause", "arbitration clause"],
        contextTip: "Luôn kiểm tra kỹ các 'penalty clause' (điều khoản phạt) trước khi ký kết.",
        topicId: "negotiation-persuasion",
        emoji: "📜",
      },
      {
        id: "np-7",
        word: "Non-negotiable",
        phonetic: "/ˌnɒn nɪˈɡoʊʃiəbl/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Không thể thương lượng, nguyên tắc cốt lõi bắt buộc tuân thủ",
        definition: "Not open to discussion or modification.",
        example: "Data privacy compliance with GDPR is completely non-negotiable for our international enterprise clients.",
        collocations: ["non-negotiable term", "strictly non-negotiable", "non-negotiable principle"],
        contextTip: "Dùng để thiết lập ranh giới (boundary setting) cứng rắn nhưng chuyên nghiệp.",
        topicId: "negotiation-persuasion",
        emoji: "🛑",
      },
      {
        id: "np-8",
        word: "Impasse",
        phonetic: "/ˈæmpæs/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Ngõ cụt, điểm thắt nút mà không có lối thoát nếu không thay đổi cách tiếp cận",
        definition: "A situation in which no progress is possible, especially because of disagreement; a deadlock.",
        example: "The mediator suggested an alternative revenue-sharing structure to overcome the political impasse.",
        collocations: ["reach an impasse", "resolve an impasse", "political impasse"],
        contextTip: "Từ vựng trang trọng (formal register), mang sắc thái trí tuệ hơn 'deadlock'.",
        topicId: "negotiation-persuasion",
        emoji: "⛔",
      },
      {
        id: "np-9",
        word: "Repertoire",
        phonetic: "/ˈrepətwɑːr/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Kho vốn kỹ năng, tập hợp chiến thuật ứng biến phong phú",
        definition: "A stock of skills or types of behavior that a person regularly uses.",
        example: "A seasoned negotiator draws from an extensive repertoire of closing strategies.",
        collocations: ["broad repertoire", "add to one's repertoire", "tactical repertoire"],
        contextTip: "Dùng để khen ngợi năng lực đa dạng và linh hoạt của một chuyên gia.",
        topicId: "negotiation-persuasion",
        emoji: "🎯",
      },
      {
        id: "np-10",
        word: "Compromise",
        phonetic: "/ˈkɒmprəmaɪz/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Giải pháp thỏa hiệp, dung hòa đôi bên cùng chấp nhận",
        definition: "An agreement or settlement of a dispute that is reached by each side making concessions.",
        example: "We found a sensible compromise between rapid delivery and stringent security audits.",
        collocations: ["reach a compromise", "strike a compromise", "compromise on price"],
        contextTip: "Lưu ý nghĩa thứ 2: 'to compromise security' nghĩa là làm suy giảm an ninh.",
        topicId: "negotiation-persuasion",
        emoji: "⚖️",
      },
    ],
  },
  {
    id: "tech-ai-innovation",
    name: "Tech, AI & Digital Transformation",
    vietnameseName: "Công Nghệ & Đổi Mới Sáng Tạo",
    description: "Bộ từ vựng công nghệ hiện đại, trí tuệ nhân tạo, kiến trúc hệ thống và chuyển đổi số.",
    iconName: "Cpu",
    level: "B2",
    accentColor: "sky",
    words: [
      {
        id: "tech-1",
        word: "Disruptive",
        phonetic: "/dɪsˈrʌptɪv/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Mang tính đột phá mang tính cách mạng, thay đổi hoàn toàn cục diện thị trường",
        definition: "Innovatively replacing an existing market, industry, or technology and producing unexpected consequences.",
        example: "Cloud computing was once considered a disruptive technology, but now it is standard practice.",
        collocations: ["disruptive innovation", "disruptive technology", "disruptive business model"],
        contextTip: "Khái niệm kinh điển của Giáo sư Clayton Christensen (Harvard Business School).",
        topicId: "tech-ai-innovation",
        emoji: "💥",
      },
      {
        id: "tech-2",
        word: "Autonomous",
        phonetic: "/ɔːˈtɒnəməs/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Tự chủ, tự động vận hành không cần can thiệp thủ công từ con người",
        definition: "Having the freedom or power to act independently; acting without direct human control.",
        example: "Our data pipelines are fully autonomous, self-healing, and dynamically scalable.",
        collocations: ["autonomous agents", "autonomous systems", "autonomous driving"],
        contextTip: "Từ khóa dẫn đầu kỷ nguyên AI Agents và robotics hiện nay.",
        topicId: "tech-ai-innovation",
        emoji: "🤖",
      },
      {
        id: "tech-3",
        word: "Latency",
        phonetic: "/ˈleɪtənsi/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Độ trễ truyền tải dữ liệu giữa lệnh gửi và phản hồi",
        definition: "The delay before a transfer of data begins following an instruction for its transfer.",
        example: "By deploying Edge CDN workers, we reduced API latency from three hundred milliseconds to under thirty.",
        collocations: ["ultra-low latency", "reduce latency", "network latency"],
        contextTip: "Chỉ số sống còn trong các hệ thống real-time audio, fintech và game.",
        topicId: "tech-ai-innovation",
        emoji: "⚡",
      },
      {
        id: "tech-4",
        word: "Robust",
        phonetic: "/roʊˈbʌst/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Mạnh mẽ, vững chắc, chịu tải và xử lý ngoại lệ tốt mà không gặp sự cố",
        definition: "Able to withstand or overcome adverse conditions; reliable and strongly built.",
        example: "We implemented a robust fault-tolerance mechanism to handle unexpected cloud region outages.",
        collocations: ["robust architecture", "robust security", "robust framework"],
        contextTip: "Từ vựng đắt giá trong code review và thuyết minh giải pháp kỹ thuật.",
        topicId: "tech-ai-innovation",
        emoji: "🛡️",
      },
      {
        id: "tech-5",
        word: "Iterative",
        phonetic: "/ˈɪtərətɪv/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Lặp lại và cải tiến liên tục qua từng chu kỳ ngắn",
        definition: "Relating to or involving repetition of a process, typically in order to achieve a desired goal or result.",
        example: "We take an iterative approach to UI design, collecting user telemetry after each two-week release.",
        collocations: ["iterative process", "iterative development", "iterative improvement"],
        contextTip: "Trái ngược với mô hình thác nước (waterfall), là cốt lõi của Agile / Scrum.",
        topicId: "tech-ai-innovation",
        emoji: "🔁",
      },
      {
        id: "tech-6",
        word: "Algorithmic",
        phonetic: "/ˌælɡəˈrɪðmɪk/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Thuộc về thuật toán, vận hành dựa trên tập quy tắc toán học tự động",
        definition: "Relating to or using a process or set of rules to be followed in calculations or other problem-solving operations.",
        example: "Algorithmic trading accounts for more than half of the daily trading volume on Wall Street.",
        collocations: ["algorithmic trading", "algorithmic bias", "algorithmic efficiency"],
        contextTip: "Thường dùng trong phân tích dữ liệu lớn và đạo đức công nghệ (AI safety).",
        topicId: "tech-ai-innovation",
        emoji: "🔢",
      },
      {
        id: "tech-7",
        word: "Deprecated",
        phonetic: "/ˈdeprəkeɪtɪd/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Lỗi thời, không còn được khuyến nghị sử dụng và sẽ bị gỡ bỏ trong tương lai",
        definition: "Declared obsolete and warned against using, though still available in software for backward compatibility.",
        example: "This legacy authentication endpoint has been deprecated and will be removed in version 3.0.",
        collocations: ["deprecated feature", "deprecated API", "mark as deprecated"],
        contextTip: "Từ ngữ chuẩn xác dân phần mềm hay dùng khi dọn dẹp mã nguồn cũ.",
        topicId: "tech-ai-innovation",
        emoji: "⚠️",
      },
      {
        id: "tech-8",
        word: "Telemetry",
        phonetic: "/təˈlemətri/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Dữ liệu đo đạc và thu thập chỉ số vận hành từ xa",
        definition: "The automatic recording and transmission of data from remote or inaccessible sources to an IT system for monitoring and analysis.",
        example: "Our real-time telemetry dashboards alert on-call engineers whenever error rates spike.",
        collocations: ["collect telemetry", "telemetry dashboard", "system telemetry"],
        contextTip: "Xuất hiện thường trực trong DevOps, APM (Datadog/NewRelic) và analytics.",
        topicId: "tech-ai-innovation",
        emoji: "📡",
      },
      {
        id: "tech-9",
        word: "Neural",
        phonetic: "/ˈnjʊərəl/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Thuộc về mạng nơ-ron nhân tạo mô phỏng bộ não con người",
        definition: "Relating to a network of interconnected neurons or artificial computing units.",
        example: "Neural machine translation produces vastly more fluent sentences than rule-based systems.",
        collocations: ["neural network", "neural processing unit", "deep neural network"],
        contextTip: "Nền tảng của Deep Learning, LLMs và Speech-to-Text Whisper.",
        topicId: "tech-ai-innovation",
        emoji: "🧠",
      },
      {
        id: "tech-10",
        word: "Proprietary",
        phonetic: "/prəˈpraɪətəri/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Độc quyền, thuộc sở hữu sở hữu trí tuệ riêng của công ty",
        definition: "Relating to an owner or ownership; protected by trademark, patent, or copyright.",
        example: "Their proprietary speech synthesis engine gives them a tremendous competitive moat.",
        collocations: ["proprietary software", "proprietary algorithm", "proprietary technology"],
        contextTip: "Đối lập với 'open-source' (mã nguồn mở).",
        topicId: "tech-ai-innovation",
        emoji: "💎",
      },
      {
        id: "tech-11",
        word: "Throughput",
        phonetic: "/ˈθruːpʊt/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Thông lượng, lượng dữ liệu hoặc số giao dịch hệ thống xử lý thành công trong một đơn vị thời gian",
        definition: "The amount of material or data that passes through a system or process.",
        example: "By clustering our worker nodes, we achieved a peak throughput of fifty thousand events per second.",
        collocations: ["high throughput", "network throughput", "maximize throughput"],
        contextTip: "Chỉ số hàng đầu khi trao đổi solution call về xử lý dữ liệu lớn.",
        topicId: "tech-ai-innovation",
        emoji: "⚡",
      },
      {
        id: "tech-12",
        word: "Decoupling",
        phonetic: "/diːˈkʌplɪŋ/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Sự phân tách, tách rời các dịch vụ để giảm thiểu sự phụ thuộc lẫn nhau trong kiến trúc",
        definition: "The separation of interconnected subsystems so that changes in one do not break others.",
        example: "Introducing a message queue enables decoupling between order processing and payment gateways.",
        collocations: ["decoupling services", "loose decoupling", "architectural decoupling"],
        contextTip: "Nguyên lý cốt lõi của Microservices và Event-driven architecture.",
        topicId: "tech-ai-innovation",
        emoji: "🧩",
      },
      {
        id: "tech-13",
        word: "Idempotent",
        phonetic: "/aɪˈdempətənt/",
        partOfSpeech: "adjective",
        level: "C2",
        meaning: "Tính lũy đẳng, đặc tính cho phép gọi một thao tác nhiều lần mà kết quả vẫn không thay đổi so với lần đầu",
        definition: "Denoting an element or operation of a system which produces the same outcome when repeated.",
        example: "Our payment processing webhook is strictly idempotent to avoid duplicate charges on network retries.",
        collocations: ["idempotent API", "idempotent request", "ensure idempotency"],
        contextTip: "Khái niệm bắt buộc khi thiết kế API thanh toán và hệ thống retry.",
        topicId: "tech-ai-innovation",
        emoji: "🔄",
      },
      {
        id: "tech-14",
        word: "Failover",
        phonetic: "/ˈfeɪloʊvər/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Cơ chế tự động chuyển đổi dự phòng sang máy chủ thứ cấp khi máy chủ chính gặp sự cố",
        definition: "A method of protecting computer systems from failure, in which standby equipment automatically takes over.",
        example: "Multi-region failover ensures our SaaS platform remains available even if an entire AWS zone goes down.",
        collocations: ["automatic failover", "disaster failover", "failover mechanism"],
        contextTip: "Cam kết sống còn trong các buổi call tư vấn giải pháp High Availability (HA).",
        topicId: "tech-ai-innovation",
        emoji: "🛡️",
      },
      {
        id: "tech-15",
        word: "Orchestration",
        phonetic: "/ˌɔːrkɪˈstreɪʃn/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Sự điều phối tự động các container, tiến trình và luồng dữ liệu phức tạp trong hệ thống",
        definition: "The automated coordination and management of complex computer systems and services.",
        example: "Kubernetes handles container orchestration, load balancing, and health check monitoring.",
        collocations: ["container orchestration", "workflow orchestration", "orchestration engine"],
        contextTip: "Từ vựng đắt giá khi nói về Kubernetes, Airflow hoặc Temporal.",
        topicId: "tech-ai-innovation",
        emoji: "🎼",
      },
      {
        id: "tech-16",
        word: "Refactoring",
        phonetic: "/riːˈfæktərɪŋ/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Tái cấu trúc mã nguồn để tăng tính đọc hiểu và hiệu năng mà không thay đổi hành vi bên ngoài",
        definition: "The process of restructuring existing computer code without changing its external behavior.",
        example: "We allocated twenty percent of the sprint to refactoring legacy database access layers.",
        collocations: ["code refactoring", "architectural refactoring", "continuous refactoring"],
        contextTip: "Dùng để giải trình về việc xử lý nợ kỹ thuật (technical debt).",
        topicId: "tech-ai-innovation",
        emoji: "🛠️",
      },
    ],
  },
  {
    id: "executive-rhetoric",
    name: "Executive Rhetoric & Presentation",
    vietnameseName: "Giao Tiếp & Hùng Biện Lãnh Đạo",
    description: "Nghệ thuật phát biểu truyền cảm hứng, lập luận sắc bén và bảo vệ quan điểm trước hội đồng.",
    iconName: "Megaphone",
    level: "C1",
    accentColor: "purple",
    words: [
      {
        id: "er-1",
        word: "Articulate",
        phonetic: "/ɑːrˈtɪkjuleɪt/",
        partOfSpeech: "verb",
        level: "C1",
        meaning: "Diễn đạt rõ ràng, gãy gọn và thuyết phục từng ý niệm phức tạp",
        definition: "Express an idea or feeling fluently and coherently in speech or writing.",
        example: "She was able to articulate the technical roadmap so clearly that non-engineers grasped it immediately.",
        collocations: ["articulate a vision", "clearly articulate", "articulate speaker"],
        contextTip: "Có thể là tính từ: 'an articulate leader' (nhà lãnh đạo hoạt ngôn, đĩnh đạc).",
        topicId: "executive-rhetoric",
        emoji: "🎙️",
      },
      {
        id: "er-2",
        word: "Cogent",
        phonetic: "/ˈkoʊdʒənt/",
        partOfSpeech: "adjective",
        level: "C2",
        meaning: "Chặt chẽ, đanh thép, có sức thuyết phục logic không thể bác bỏ",
        definition: "Clear, logical, and convincing in argument.",
        example: "The CFO presented a cogent economic argument for automating warehouse logistics.",
        collocations: ["cogent argument", "cogent reasoning", "cogent evidence"],
        contextTip: "Từ cấp cao thể hiện tư duy phản biện sắc sảo bậc nhất.",
        topicId: "executive-rhetoric",
        emoji: "🧠",
      },
      {
        id: "er-3",
        word: "Succinct",
        phonetic: "/səkˈsɪŋkt/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Ngắn gọn, súc tích, đi thẳng vào trọng tâm không rườm rà",
        definition: "Briefly and clearly expressed, without unnecessary words.",
        example: "Please keep your weekly executive status updates succinct and data-driven.",
        collocations: ["succinct summary", "succinct explanation", "short and succinct"],
        contextTip: "Đặc điểm tối quan trọng khi viết email báo cáo gửi Giám đốc hoặc C-Level.",
        topicId: "executive-rhetoric",
        emoji: "✂️",
      },
      {
        id: "er-4",
        word: "Compelling",
        phonetic: "/kəmˈpelɪŋ/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Hấp dẫn, lôi cuốn, thôi thúc người khác phải đồng ý hoặc hành động",
        definition: "Evoking interest, attention, or admiration in a powerfully irresistible way.",
        example: "The product pitch told a compelling story about how customer pain points were solved.",
        collocations: ["compelling narrative", "compelling case", "compelling reason"],
        contextTip: "Dùng để khen ngợi bài thuyết trình: 'That was a truly compelling pitch!'.",
        topicId: "executive-rhetoric",
        emoji: "🔥",
      },
      {
        id: "er-5",
        word: "Nuanced",
        phonetic: "/ˈnjuːɑːnst/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Tinh tế, đa chiều, nhìn nhận được các tầng lớp chi tiết sâu xa",
        definition: "Characterized by subtle distinctions or variations in meaning, sound, or physical appearance.",
        example: "We need a nuanced approach to global market entry that respects local cultural differences.",
        collocations: ["nuanced understanding", "nuanced perspective", "nuanced policy"],
        contextTip: "Trái ngược với cách nhìn nhận sự việc đen trắng một chiều (black-and-white).",
        topicId: "executive-rhetoric",
        emoji: "🎨",
      },
      {
        id: "er-6",
        word: "Candid",
        phonetic: "/ˈkændɪd/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Thẳng thắn, chân thành, bộc trực mà không giấu giếm",
        definition: "Truthful and straightforward; frank.",
        example: "I appreciate your candid feedback on the prototype; it highlighted several flaws we overlooked.",
        collocations: ["candid feedback", "candid conversation", "be candid with someone"],
        contextTip: "Cụm 'To be completely candid...' là cách mở đầu phản biện rất văn minh.",
        topicId: "executive-rhetoric",
        emoji: "🤝",
      },
      {
        id: "er-7",
        word: "Rhetoric",
        phonetic: "/ˈretərɪk/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Nghệ thuật tu từ, thuật hùng biện tác động tâm lý người nghe",
        definition: "The art of effective or persuasive speaking or writing, especially using figures of speech.",
        example: "Behind the marketing rhetoric, our engineers focus on verifiable benchmark numbers.",
        collocations: ["political rhetoric", "empty rhetoric", "powerful rhetoric"],
        contextTip: "Có thể mang sắc thái trung tính (nghệ thuật diễn thuyết) hoặc tiêu cực (lời nói sáo rỗng).",
        topicId: "executive-rhetoric",
        emoji: "🗣️",
      },
      {
        id: "er-8",
        word: "Cohesive",
        phonetic: "/koʊˈhiːsɪv/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Gắn kết chặt chẽ, tạo thành một chỉnh thể thống nhất và ăn khớp",
        definition: "Characterized by or causing cohesion; forming a united whole.",
        example: "The presentation felt cohesive because each slide directly supported the primary thesis.",
        collocations: ["cohesive narrative", "cohesive team", "cohesive strategy"],
        contextTip: "Quan trọng cho cả kỹ năng thuyết trình lẫn kỹ năng lãnh đạo đội ngũ.",
        topicId: "executive-rhetoric",
        emoji: "🔗",
      },
      {
        id: "er-9",
        word: "Eloquent",
        phonetic: "/ˈeləkwənt/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Hùng hồn, trau chuốt, có tài diễn thuyết lay động lòng người",
        definition: "Fluent or persuasive in speaking or writing.",
        example: "The founder delivered an eloquent defense of open internet access at the conference.",
        collocations: ["eloquent speech", "eloquent speaker", "eloquent testimony"],
        contextTip: "Lời khen ngợi trang trọng nhất dành cho một diễn giả xuất chúng.",
        topicId: "executive-rhetoric",
        emoji: "🎤",
      },
      {
        id: "er-10",
        word: "Substantiate",
        phonetic: "/səbˈstænʃieɪt/",
        partOfSpeech: "verb",
        level: "C2",
        meaning: "Đưa ra bằng chứng xác thực để chứng minh một tuyên bố",
        definition: "Provide evidence to support or prove the truth of something.",
        example: "Can you provide quantitative customer survey data to substantiate this market projection?",
        collocations: ["substantiate a claim", "substantiate allegations", "substantiate findings"],
        contextTip: "Dùng khi chất vấn các đề xuất dự án thiếu số liệu thực chứng.",
        topicId: "executive-rhetoric",
        emoji: "🔍",
      },
    ],
  },
  {
    id: "finance-growth",
    name: "Finance, Investment & Valuation",
    vietnameseName: "Tài Chính & Đầu Tư Tăng Trưởng",
    description: "Bộ thuật ngữ tài chính doanh nghiệp, định giá tài sản, dòng tiền và chỉ số sinh lời.",
    iconName: "TrendingUp",
    level: "B2",
    accentColor: "emerald",
    words: [
      {
        id: "fg-1",
        word: "Liquidity",
        phonetic: "/lɪˈkwɪdəti/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Tính thanh khoản, khả năng chuyển đổi tài sản thành tiền mặt nhanh chóng",
        definition: "The availability of liquid assets to a market or company; the ease with which an asset can be converted into cash.",
        example: "Maintaining adequate liquidity is vital to weather unexpected downturns in consumer demand.",
        collocations: ["cash liquidity", "market liquidity", "liquidity crisis"],
        contextTip: "Mạch máu tài chính của mọi doanh nghiệp và quỹ đầu tư mạo hiểm.",
        topicId: "finance-growth",
        emoji: "💧",
      },
      {
        id: "fg-2",
        word: "Dividend",
        phonetic: "/ˈdɪvɪdend/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Cổ tức, khoản lợi nhuận chia cho các cổ đông định kỳ",
        definition: "A sum of money paid regularly by a company to its shareholders out of its profits.",
        example: "The board voted to increase the quarterly dividend payout by eight percent.",
        collocations: ["dividend yield", "pay a dividend", "dividend payout ratio"],
        contextTip: "Thường dùng trong báo cáo tài chính hàng quý (quarterly earnings calls).",
        topicId: "finance-growth",
        emoji: "💰",
      },
      {
        id: "fg-3",
        word: "Margin",
        phonetic: "/ˈmɑːrdʒɪn/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Biên lợi nhuận, tỷ lệ phần trăm giữa doanh thu và chi phí",
        definition: "The difference between the cost of producing something and the price at which it is sold.",
        example: "Our transition to digital distribution expanded our operating margin by twelve percentage points.",
        collocations: ["gross margin", "profit margin", "operating margin"],
        contextTip: "Luôn phân biệt 'gross margin' (biên lợi nhuận gộp) và 'net margin' (biên ròng).",
        topicId: "finance-growth",
        emoji: "📊",
      },
      {
        id: "fg-4",
        word: "Volatility",
        phonetic: "/ˌvɒləˈtɪləti/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Độ biến động, mức độ thăng trầm khó lường của giá cả hoặc thị trường",
        definition: "Liability to change rapidly and unpredictably, especially for the worse.",
        example: "Hedging strategies help protect our portfolio against foreign exchange rate volatility.",
        collocations: ["market volatility", "high volatility", "price volatility"],
        contextTip: "Từ vựng cơ bản khi thảo luận về quản trị rủi ro đầu tư (risk management).",
        topicId: "finance-growth",
        emoji: "📉",
      },
      {
        id: "fg-5",
        word: "Fiscal",
        phonetic: "/ˈfɪskl/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Thuộc về tài khóa, ngân sách tài chính của năm hoạt động",
        definition: "Relating to government or corporate revenue, especially taxes and financial budgeting.",
        example: "Our company closed fiscal year 2025 with record annual recurring revenue.",
        collocations: ["fiscal year", "fiscal policy", "fiscal discipline"],
        contextTip: "Viết tắt là FY (ví dụ: FY2026 = Năm tài chính 2026).",
        topicId: "finance-growth",
        emoji: "📅",
      },
      {
        id: "fg-6",
        word: "Capitalize",
        phonetic: "/ˈkæpɪtəlaɪz/",
        partOfSpeech: "verb",
        level: "C1",
        meaning: "Tận dụng cơ hội sinh lời hoặc ghi nhận chi phí thành tài sản vốn hóa",
        definition: "Take the chance to gain advantage from; or to provide with capital.",
        example: "We must capitalize on this emerging market window before competing incumbents react.",
        collocations: ["capitalize on an opportunity", "capitalize a cost", "well-capitalized"],
        contextTip: "Cụm từ thông dụng: 'capitalize on...' = nắm bắt thời cơ vàng.",
        topicId: "finance-growth",
        emoji: "🏦",
      },
      {
        id: "fg-7",
        word: "Valuation",
        phonetic: "/ˌvæljuˈeɪʃn/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Định giá doanh nghiệp, ước tính giá trị tiền tệ của công ty",
        definition: "An estimation of the worth of something, especially by a professional appraiser.",
        example: "The Series B funding round pegged the software company's valuation at one billion dollars.",
        collocations: ["market valuation", "high valuation", "pre-money valuation"],
        contextTip: "Thuật ngữ cốt lõi trong giới Venture Capital (VC) và M&A.",
        topicId: "finance-growth",
        emoji: "🏷️",
      },
      {
        id: "fg-8",
        word: "Solvency",
        phonetic: "/ˈsɒlvənsi/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Khả năng thanh toán nợ dài hạn, tình trạng tài chính lành mạnh",
        definition: "The possession of assets in excess of liabilities; ability to pay one's debts.",
        example: "Strict balance sheet audits guaranteed the ongoing solvency of the regional credit union.",
        collocations: ["long-term solvency", "threaten solvency", "solvency ratio"],
        contextTip: "Khác với 'liquidity' (ngắn hạn), 'solvency' phản ánh sức khỏe tài chính trường tồn.",
        topicId: "finance-growth",
        emoji: "🏛️",
      },
      {
        id: "fg-9",
        word: "Amortization",
        phonetic: "/əˌmɔːrtɪˈzeɪʃn/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Khấu hao tài sản vô hình hoặc trả góp dần nợ gốc định kỳ",
        definition: "The action or process of gradually writing off the initial cost of an asset or repaying a debt.",
        example: "The financial report clearly separated depreciation from patent amortization schedules.",
        collocations: ["amortization schedule", "loan amortization", "goodwill amortization"],
        contextTip: "Nằm trong chỉ số EBITDA kinh điển (Earnings Before Interest, Taxes, Depreciation, and Amortization).",
        topicId: "finance-growth",
        emoji: "📜",
      },
      {
        id: "fg-10",
        word: "Revenue",
        phonetic: "/ˈrevənjuː/",
        partOfSpeech: "noun",
        level: "B1",
        meaning: "Doanh thu tổng, toàn bộ số tiền thu vào từ hoạt động bán hàng",
        definition: "Income, especially when of a company or organization and of a substantial nature.",
        example: "Recurring subscription revenue accounted for over eighty percent of our total gross income.",
        collocations: ["annual revenue", "recurring revenue (ARR)", "generate revenue"],
        contextTip: "Doanh thu là 'top-line', còn lợi nhuận ròng là 'bottom-line'.",
        topicId: "finance-growth",
        emoji: "💵",
      },
    ],
  },
  {
    id: "leadership-mindset",
    name: "Leadership Mindset & Cognitive Agility",
    vietnameseName: "Tư Duy Lãnh Đạo & Tâm Lý Học",
    description: "Bộ từ vựng về trí tuệ cảm xúc, sự kiên định, thích ứng linh hoạt và quản trị con người.",
    iconName: "Brain",
    level: "C1",
    accentColor: "sky",
    words: [
      {
        id: "lm-1",
        word: "Resilience",
        phonetic: "/rɪˈzɪliəns/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Nghị lực bền bỉ, khả năng phục hồi và đứng dậy nhanh sau khủng hoảng",
        definition: "The capacity to withstand or to recover quickly from difficulties; toughness.",
        example: "The leadership team showed exceptional resilience while steering the company through the pandemic.",
        collocations: ["mental resilience", "build resilience", "organizational resilience"],
        contextTip: "Phẩm chất số một được tìm kiếm ở các nhà quản lý thời đại biến động.",
        topicId: "leadership-mindset",
        emoji: "🌱",
      },
      {
        id: "lm-2",
        word: "Empathy",
        phonetic: "/ˈempəθi/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Sự thấu cảm, khả năng đặt mình vào vị trí và cảm xúc của người khác",
        definition: "The ability to understand and share the feelings of another.",
        example: "Leading with empathy builds psychological safety and fosters fearless experimentation.",
        collocations: ["lead with empathy", "deep empathy", "empathy for users"],
        contextTip: "Khác với 'sympathy' (thương hại), 'empathy' là thấu hiểu trọn vẹn từ góc nhìn đối phương.",
        topicId: "leadership-mindset",
        emoji: "❤️",
      },
      {
        id: "lm-3",
        word: "Grit",
        phonetic: "/ɡrɪt/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Lòng can trường, sự kiên trì theo đuổi mục tiêu dài hạn bất chấp khó khăn",
        definition: "Courage and resolve; strength of character combined with perseverance.",
        example: "Raw talent is common, but sustained grit is what separates great leaders from the rest.",
        collocations: ["unwavering grit", "show grit", "grit and determination"],
        contextTip: "Thuật ngữ tâm lý nổi tiếng của Angela Duckworth (TED Talk kinh điển).",
        topicId: "leadership-mindset",
        emoji: "🧗",
      },
      {
        id: "lm-4",
        word: "Intrinsic",
        phonetic: "/ɪnˈtrɪnzɪk/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Thuộc về nội tại, xuất phát từ bản chất hoặc đam mê bên trong",
        definition: "Belonging naturally; essential; originating from within.",
        example: "The most innovative teams are driven by intrinsic motivation rather than external bonuses.",
        collocations: ["intrinsic motivation", "intrinsic value", "intrinsic quality"],
        contextTip: "Đối lập với 'extrinsic' (ngoại tại, áp lực từ bên ngoài).",
        topicId: "leadership-mindset",
        emoji: "🌟",
      },
      {
        id: "lm-5",
        word: "Cognitive",
        phonetic: "/ˈkɒɡnətɪv/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Thuộc về nhận thức, quá trình tư duy, xử lý thông tin và lý luận của trí não",
        definition: "Relating to cognition; concerned with the act or process of knowing, perceiving, etc.",
        example: "Excessive context-switching creates cognitive overload and degrades executive decision quality.",
        collocations: ["cognitive bias", "cognitive load", "cognitive agility"],
        contextTip: "Cụm 'cognitive overload' (quá tải nhận thức) rất phổ biến trong môi trường làm việc số.",
        topicId: "leadership-mindset",
        emoji: "🧩",
      },
      {
        id: "lm-6",
        word: "Decisive",
        phonetic: "/dɪˈsaɪsɪv/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Quyết đoán, dứt khoát đưa ra hành động mà không do dự",
        definition: "Settling an issue; producing a definite result; showing the ability to make decisions quickly and effectively.",
        example: "When the supply chain failed, our VP took decisive action to contract alternative suppliers.",
        collocations: ["decisive leader", "decisive factor", "take decisive action"],
        contextTip: "Phẩm chất tối thượng của một thuyền trưởng trong cơn giông bão.",
        topicId: "leadership-mindset",
        emoji: "⚔️",
      },
      {
        id: "lm-7",
        word: "Bias",
        phonetic: "/ˈbaɪəs/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Định kiến, thiên kiến tâm lý dẫn đến nhận định sai lệch",
        definition: "Prejudice in favor of or against one thing, person, or group compared with another, usually in an unfair way.",
        example: "Our hiring committee undergoes regular training to eliminate unconscious gender and racial bias.",
        collocations: ["unconscious bias", "confirmation bias", "eliminate bias"],
        contextTip: "'Confirmation bias' (thiên kiến xác nhận) là xu hướng chỉ tin thông tin ủng hộ ý kiến cũ của mình.",
        topicId: "leadership-mindset",
        emoji: "⚖️",
      },
      {
        id: "lm-8",
        word: "Catalyst",
        phonetic: "/ˈkætəlɪst/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Chất xúc tác, người hoặc sự kiện thúc đẩy thay đổi diễn ra nhanh hơn",
        definition: "A person or thing that precipitates an event or accelerates change.",
        example: "The new engineering lead acted as a catalyst for a more open and collaborative culture.",
        collocations: ["act as a catalyst", "catalyst for change", "catalyst for growth"],
        contextTip: "Từ vựng giàu hình tượng dùng trong khen thưởng và bổ nhiệm lãnh đạo.",
        topicId: "leadership-mindset",
        emoji: "🧪",
      },
      {
        id: "lm-9",
        word: "Adaptability",
        phonetic: "/əˌdæptəˈbɪləti/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Khả năng thích ứng linh hoạt trước những điều kiện mới bất ngờ",
        definition: "The quality of being able to adjust to new conditions.",
        example: "In a fast-evolving AI landscape, adaptability matters far more than fixed domain knowledge.",
        collocations: ["high adaptability", "demonstrate adaptability", "career adaptability"],
        contextTip: "AQ (Adaptability Quotient) ngày nay được đánh giá cao ngang ngửa IQ và EQ.",
        topicId: "leadership-mindset",
        emoji: "🦎",
      },
      {
        id: "lm-10",
        word: "Accountability",
        phonetic: "/əˌkaʊntəˈbɪləti/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Trách nhiệm giải trình, tinh thần chịu trách nhiệm cao nhất về kết quả cuối cùng",
        definition: "The fact or condition of being accountable; responsibility.",
        example: "Clear team ownership ensures transparency and fosters individual accountability.",
        collocations: ["hold someone accountable", "mutual accountability", "promote accountability"],
        contextTip: "Cụm 'hold someone accountable' nghĩa là yêu cầu ai đó chịu trách nhiệm về lời hứa.",
        topicId: "leadership-mindset",
        emoji: "📌",
      },
    ],
  },
  {
    id: "global-lifestyle",
    name: "Cross-Cultural Banter & Diplomatic Etiquette",
    vietnameseName: "Đời Sống Quốc Tế & Nghi Thức Ngoại Giao",
    description: "Bộ từ vựng giao tiếp tinh tế, chuẩn mực văn hóa quốc tế, tiệc tối ngoại giao và du lịch cao cấp.",
    iconName: "Compass",
    level: "B2",
    accentColor: "indigo",
    words: [
      {
        id: "gl-1",
        word: "Cosmopolitan",
        phonetic: "/ˌkɒzməˈpɒlɪtən/",
        partOfSpeech: "adjective",
        level: "C1",
        meaning: "Mang tính quốc tế, mở rộng tầm nhìn toàn cầu từ nhiều nền văn hóa giao thoa",
        definition: "Familiar with and at ease in many different countries and cultures.",
        example: "Singapore and London are renowned for their vibrant, cosmopolitan atmosphere.",
        collocations: ["cosmopolitan city", "cosmopolitan outlook", "cosmopolitan lifestyle"],
        contextTip: "Dùng để mô tả lối sống văn minh, không bị bó hẹp trong tư duy địa phương.",
        topicId: "global-lifestyle",
        emoji: "🌍",
      },
      {
        id: "gl-2",
        word: "Etiquette",
        phonetic: "/ˈetɪket/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Nghi thức, quy tắc ứng xử lịch thiệp chuẩn mực trong xã hội hoặc giới kinh doanh",
        definition: "The customary code of polite behavior in society or among members of a particular profession or group.",
        example: "Understanding local business dining etiquette is crucial when hosting partners from Japan.",
        collocations: ["dining etiquette", "business etiquette", "breach of etiquette"],
        contextTip: "Chú ý phát âm: trọng âm rơi vào âm tiết đầu tiên /ˈetɪket/.",
        topicId: "global-lifestyle",
        emoji: "🎩",
      },
      {
        id: "gl-3",
        word: "Protocol",
        phonetic: "/ˈproʊtəkɒl/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Nghi thức ngoại giao chính thức hoặc quy trình thủ tục nghiêm ngặt",
        definition: "The official procedure or system of rules governing affairs of state or diplomatic occasions.",
        example: "Diplomatic protocol dictated the exact seating arrangement for the visiting ministers.",
        collocations: ["diplomatic protocol", "standard protocol", "follow protocol"],
        contextTip: "Có cả nghĩa trong công nghệ (Network protocol như HTTP, TCP/IP).",
        topicId: "global-lifestyle",
        emoji: "🏛️",
      },
      {
        id: "gl-4",
        word: "Contemporary",
        phonetic: "/kənˈtempərəri/",
        partOfSpeech: "adjective",
        level: "B2",
        meaning: "Đương đại, hiện đại, mang hơi thở của thời điểm hiện tại",
        definition: "Living or occurring at the same time; belonging to or occurring in the present.",
        example: "The boutique hotel features a stunning collection of contemporary Southeast Asian artwork.",
        collocations: ["contemporary art", "contemporary architecture", "contemporary society"],
        contextTip: "Chủ đề đắc địa khi trò chuyện networking về nghệ thuật, kiến trúc và lối sống.",
        topicId: "global-lifestyle",
        emoji: "🖼️",
      },
      {
        id: "gl-5",
        word: "Ambiance",
        phonetic: "/ˌɑːmbiˈɑːns/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Bầu không khí, phong vị cảm xúc bao trùm một không gian hoặc địa điểm",
        definition: "The character and atmosphere of a place.",
        example: "The private rooftop lounge provided an intimate ambiance perfect for closing the partnership deal.",
        collocations: ["warm ambiance", "relaxed ambiance", "elegant ambiance"],
        contextTip: "Từ gốc Pháp, tạo cảm giác sang trọng khi miêu tả nhà hàng hoặc khách sạn 5 sao.",
        topicId: "global-lifestyle",
        emoji: "🍷",
      },
      {
        id: "gl-6",
        word: "Expatriate",
        phonetic: "/ekˈspætriət/",
        partOfSpeech: "noun",
        level: "C1",
        meaning: "Chuyên gia hoặc người định cư, làm việc tại nước ngoài (thường gọi tắt là expat)",
        definition: "A person who lives outside their native country, often for professional commitments.",
        example: "The city has a thriving expatriate community with numerous international networking clubs.",
        collocations: ["expatriate community", "expat package", "relocate as an expat"],
        contextTip: "Thường dùng dạng rút gọn thân mật là 'expat'.",
        topicId: "global-lifestyle",
        emoji: "✈️",
      },
      {
        id: "gl-7",
        word: "Itinerary",
        phonetic: "/aɪˈtɪnərəri/",
        partOfSpeech: "noun",
        level: "B2",
        meaning: "Lịch trình chuyến công tác hoặc kế hoạch di chuyển chi tiết",
        definition: "A planned route or journey; a travel document recording a route.",
        example: "Our executive assistant sent over the finalized travel itinerary for the European summit.",
        collocations: ["travel itinerary", "detailed itinerary", "packed itinerary"],
        contextTip: "Nhấn âm 2 /aɪˈtɪnərəri/, không đọc là 'i-ti-ne-ra-ry'.",
        topicId: "global-lifestyle",
        emoji: "🗺️",
      },
      {
        id: "gl-8",
        word: "Decorum",
        phonetic: "/dɪˈkɔːrəm/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Sự đoan trang, phong thái đĩnh đạc và hành xử đúng mực nơi công cộng",
        definition: "Behavior in keeping with good taste and propriety; polite and socially acceptable behavior.",
        example: "Despite the heated debate, all board members maintained impeccable professional decorum.",
        collocations: ["maintain decorum", "professional decorum", "sense of decorum"],
        contextTip: "Từ ngữ quý phái, dùng để ca ngợi tác phong lịch lãm trong môi trường chuyên nghiệp.",
        topicId: "global-lifestyle",
        emoji: "🤵",
      },
      {
        id: "gl-9",
        word: "Hospitality",
        phonetic: "/ˌhɒspɪˈtæləti/",
        partOfSpeech: "noun",
        level: "B1",
        meaning: "Sự hiếu khách, lòng nồng hậu đón tiếp đối tác hoặc ngành dịch vụ lưu trú",
        definition: "The friendly and generous reception and entertainment of guests, visitors, or strangers.",
        example: "We deeply appreciate the gracious hospitality extended to our delegation during the visit.",
        collocations: ["generous hospitality", "hospitality industry", "warm hospitality"],
        contextTip: "Cụm 'extend hospitality' là cách nói chuẩn mực ngoại giao khi cảm ơn chủ nhà.",
        topicId: "global-lifestyle",
        emoji: "🥂",
      },
      {
        id: "gl-10",
        word: "Savoir-faire",
        phonetic: "/ˌsævwɑː ˈfeər/",
        partOfSpeech: "noun",
        level: "C2",
        meaning: "Sự khéo léo trong ứng xử xã hội, biết nói và làm đúng lúc đúng chỗ một cách duyên dáng",
        definition: "The ability to act or speak appropriately in social situations; social tact.",
        example: "His diplomatic savoir-faire smoothly diffused what could have been an awkward cultural misunderstanding.",
        collocations: ["diplomatic savoir-faire", "social savoir-faire", "possess savoir-faire"],
        contextTip: "Từ mượn tiếng Pháp được giới ngoại giao và giới thượng lưu phương Tây rất ưa chuộng.",
        topicId: "global-lifestyle",
        emoji: "💎",
      },
    ],
  },
];

// Helper to flatten all words from all topics
export function getAllTopicWords(): VocabTopicWord[] {
  return VOCAB_TOPICS.flatMap((t) => t.words);
}
